'use client'

// One shape for two kinds of checklist.
//
// The eight in lib/checklists.js ship with the portal: they are the site's own
// procedures, written to ISO 14644-3 Annex B and EU GMP Annex 1, and the
// library shows them under From System. Anything built on the Create screen is
// a row in the database under My Organization.
//
// The product keeps exactly this split, and it is not cosmetic: a system
// checklist is read-only and can only be duplicated, an organization one can be
// edited, archived and deleted. Resolving both to one shape here means the three
// screens read one thing and the two sources stay honestly separate underneath.
//
// The rule that matters: an organization row carrying a system id *replaces*
// the system one. That is how a site takes a procedure we shipped, edits a step,
// and has the edited one be what its technicians open — the same merge rule the
// record store uses everywhere else in this portal.

import { TEMPLATES, allItems, allItemsOf, codeFor, CATEGORIES } from './checklists'

export { CATEGORIES }

/**
 * Guess a category from a checklist's name.
 *
 * Used only to pre-fill the create form, where a wrong guess costs one click
 * and a missing one costs the author a decision they did not need to make.
 */
export function categoryFor(name = '') {
  const s = String(name).toLowerCase()
  if (/gown|personnel|operator|training|hygiene/.test(s)) return 'Personnel'
  if (/particle|viable|monitor|environment|settle|plate|count/.test(s)) return 'Environmental'
  if (/integrity|dop|pao|certif|scan|penetration|filter change|changeover/.test(s)) return 'Certification'
  return 'Facility'
}

const idOf = (c) => c.templateId || c.id || c.recordId

/**
 * A stored checklist, read as the library reads a shipped one.
 *
 * Counts and capture flags are derived rather than stored. A stored count is a
 * count that drifts out of step with the list it counts, and the first time it
 * does the reader stops trusting both.
 */
export function normalise(raw) {
  const key = idOf(raw)
  const sections = Array.isArray(raw.sections) ? raw.sections : []
  const flat = sections.length ? allItemsOf(sections) : allItems(raw)

  return {
    ...raw,
    id: key,
    key,
    name: raw.name || raw.checklistName || 'Untitled checklist',
    standard: raw.standard || '—',
    what: raw.what || raw.description || '',
    description: raw.description || raw.what || '',
    sections,
    items: flat.map((i) => i.description),
    itemCount: flat.length,
    sectionCount: sections.length,
    criticalCount: flat.filter((i) => i.critical).length,
    requiredCount: flat.filter((i) => i.required !== false).length,
    photoCount: flat.filter((i) => i.requiresPhoto).length,
    requiresPhotos: flat.some((i) => i.requiresPhoto),
    requiresSignature: flat.some((i) => i.requiresSignature),
    category: raw.category || categoryFor(raw.name || raw.checklistName),
    code: raw.code || codeFor(key),
    assetLevel: raw.assetLevel || 'Any',
    locationType: raw.locationType || '',
    scoringMethod: raw.scoringMethod || 'Pass_Fail',
    passingScore: raw.passingScore ?? 80,
    version: raw.version || '1.0',
    author: raw.author || raw.createdBy || raw._createdByName || '—',
    createdAt: raw.createdAt || raw._createdAt || null,
    modifiedAt: raw.modifiedAt || null,
    modifiedBy: raw.modifiedBy || null,
    archived: Boolean(raw.archived),
    source: raw.source === 'system' ? 'system' : 'org',
    // Carried through so the card can say a draft came out of the generator and
    // where its steps came from. Never set by this function — a checklist is
    // only marked generated by the thing that generated it.
    generatedBy: raw.generatedBy || null,
    sources: raw.sources || null,
  }
}

/** The shipped procedures, in the library shape. */
export const SYSTEM_CHECKLISTS = TEMPLATES.map((t) => normalise({ ...t, source: 'system' }))

/**
 * Everything the library holds, shipped and authored, deduplicated by id.
 *
 * @param authored the `hepa_checklist` rows out of the record store
 */
export function libraryOf(authored = []) {
  const byKey = new Map(SYSTEM_CHECKLISTS.map((c) => [c.key, c]))
  for (const row of authored) {
    const e = normalise(row)
    const existing = byKey.get(e.key)
    // An edit to a shipped procedure keeps its sections when the stored row
    // only carried the archive flag — archiving a system checklist writes a row
    // with nothing else on it, and a merge that lost the steps would empty it.
    byKey.set(e.key, existing && !e.sections.length
      ? { ...existing, ...row, archived: Boolean(row.archived), source: existing.source }
      : e)
  }
  return [...byKey.values()]
}

// Capture features are properties of a checklist, not states of one, so they
// are drawn neutral. Critical keeps its colour: it is the only one of the three
// that changes what happens when a step fails.
export const FEATURE_TONE = {
  Photos: 'slate',
  Signature: 'slate',
  Critical: 'red',
}

/** The capture features a card lists, in the product's own order. */
export function featuresOf(c) {
  return [
    c.requiresPhotos ? 'Photos' : null,
    c.requiresSignature ? 'Signature' : null,
    c.criticalCount > 0 ? 'Critical' : null,
  ].filter(Boolean)
}
