// GENERATED by scripts/import-dhl-gse-workbook.mjs — do not edit by hand.
// Source: data-source/DHL_CVG_GSE_5Year_CMMS_Demo.xlsx (00_Cover, 02_Fleet_Snapshot, 10_Work_Orders (monthly))
//
// Synthetic, operationally patterned demo data — not DHL actuals. Values are the
// sheet's own. Dates are stored exactly as supplied; the shift that keeps the
// demo current happens at read time in ./index.js.

export const META = {
  "source": "DHL_CVG_GSE_5Year_CMMS_Demo.xlsx",
  "asOf": "2026-09-15",
  "windowStart": "2021-09-16",
  "liveWindowDays": 365,
  "counts": {
    "assets": 150,
    "users": 25,
    "parts": 394,
    "manuals": 117,
    "meterReadings": 1655,
    "workOrders": 2769,
    "liveWorkOrders": 631,
    "purchaseOrders": 170,
    "poLines": 909,
    "oos": 843
  },
  "fleet": [
    {
      "Class": "Power",
      "EquipmentType": "Baggage Tractor",
      "FleetCount_CVG": 267,
      "TypicalUnitCostUSD": 42000,
      "TypicalHoursPerYear": 1800,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 11214000
    },
    {
      "Class": "Power",
      "EquipmentType": "Cargo Tractor / Bobtail",
      "FleetCount_CVG": 96,
      "TypicalUnitCostUSD": 78000,
      "TypicalHoursPerYear": 1600,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 7488000
    },
    {
      "Class": "Power",
      "EquipmentType": "Belt Loader",
      "FleetCount_CVG": 133,
      "TypicalUnitCostUSD": 55000,
      "TypicalHoursPerYear": 1400,
      "PMHoursInterval": 150,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 7315000
    },
    {
      "Class": "Power",
      "EquipmentType": "ULD / Pallet Cargo Loader",
      "FleetCount_CVG": 85,
      "TypicalUnitCostUSD": 285000,
      "TypicalHoursPerYear": 900,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 24225000
    },
    {
      "Class": "Power",
      "EquipmentType": "Pushback Tractor",
      "FleetCount_CVG": 57,
      "TypicalUnitCostUSD": 195000,
      "TypicalHoursPerYear": 700,
      "PMHoursInterval": 500,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 11115000
    },
    {
      "Class": "Power",
      "EquipmentType": "Towbarless Tractor",
      "FleetCount_CVG": 28,
      "TypicalUnitCostUSD": 320000,
      "TypicalHoursPerYear": 650,
      "PMHoursInterval": 500,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 8960000
    },
    {
      "Class": "Power",
      "EquipmentType": "Ground Power Unit",
      "FleetCount_CVG": 95,
      "TypicalUnitCostUSD": 68000,
      "TypicalHoursPerYear": 800,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 6460000
    },
    {
      "Class": "Power",
      "EquipmentType": "Air Start Unit",
      "FleetCount_CVG": 28,
      "TypicalUnitCostUSD": 95000,
      "TypicalHoursPerYear": 400,
      "PMHoursInterval": 300,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 2660000
    },
    {
      "Class": "Power",
      "EquipmentType": "PCA / Preconditioned Air",
      "FleetCount_CVG": 28,
      "TypicalUnitCostUSD": 72000,
      "TypicalHoursPerYear": 500,
      "PMHoursInterval": 250,
      "DefaultPower": "Electric",
      "EstReplacementValueUSD": 2016000
    },
    {
      "Class": "Power",
      "EquipmentType": "Lavatory Service Truck",
      "FleetCount_CVG": 19,
      "TypicalUnitCostUSD": 88000,
      "TypicalHoursPerYear": 600,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 1672000
    },
    {
      "Class": "Power",
      "EquipmentType": "Potable Water Truck",
      "FleetCount_CVG": 14,
      "TypicalUnitCostUSD": 82000,
      "TypicalHoursPerYear": 500,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 1148000
    },
    {
      "Class": "Power",
      "EquipmentType": "Forklift / Pallet Jack Powered",
      "FleetCount_CVG": 47,
      "TypicalUnitCostUSD": 38000,
      "TypicalHoursPerYear": 1100,
      "PMHoursInterval": 250,
      "DefaultPower": "LPG",
      "EstReplacementValueUSD": 1786000
    },
    {
      "Class": "Power",
      "EquipmentType": "Crew / Ramp Vehicle",
      "FleetCount_CVG": 24,
      "TypicalUnitCostUSD": 45000,
      "TypicalHoursPerYear": 900,
      "PMHoursInterval": 250,
      "DefaultPower": "Gasoline",
      "EstReplacementValueUSD": 1080000
    },
    {
      "Class": "Power",
      "EquipmentType": "Mobile GSE Charger Cart",
      "FleetCount_CVG": 14,
      "TypicalUnitCostUSD": 62000,
      "TypicalHoursPerYear": 2000,
      "PMHoursInterval": 500,
      "DefaultPower": "Electric",
      "EstReplacementValueUSD": 868000
    },
    {
      "Class": "Power",
      "EquipmentType": "Scissor Lift / Maintenance Stand Powered",
      "FleetCount_CVG": 14,
      "TypicalUnitCostUSD": 28000,
      "TypicalHoursPerYear": 400,
      "PMHoursInterval": 250,
      "DefaultPower": "Electric",
      "EstReplacementValueUSD": 392000
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Baggage Cart",
      "FleetCount_CVG": 1007,
      "TypicalUnitCostUSD": 2200,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 2215400
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "ULD Dolly / Pallet Dolly",
      "FleetCount_CVG": 848,
      "TypicalUnitCostUSD": 4500,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 3816000
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Container / Igloo Dolly",
      "FleetCount_CVG": 212,
      "TypicalUnitCostUSD": 3800,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 805600
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Aircraft Towbar",
      "FleetCount_CVG": 159,
      "TypicalUnitCostUSD": 6500,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 1033500
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Passenger Stairs (towable)",
      "FleetCount_CVG": 80,
      "TypicalUnitCostUSD": 18000,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 1440000
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Work Stand / Maintenance Dock",
      "FleetCount_CVG": 80,
      "TypicalUnitCostUSD": 8500,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 680000
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Chock / Cone Set",
      "FleetCount_CVG": 106,
      "TypicalUnitCostUSD": 180,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 19080
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Cargo Net / Restraint Kit",
      "FleetCount_CVG": 80,
      "TypicalUnitCostUSD": 420,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 33600
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Fuel / Hydrant Cart (non-power)",
      "FleetCount_CVG": 40,
      "TypicalUnitCostUSD": 12000,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 480000
    },
    {
      "Class": "Non-Power",
      "EquipmentType": "Spare Wheel / Tire Cage",
      "FleetCount_CVG": 40,
      "TypicalUnitCostUSD": 900,
      "TypicalHoursPerYear": 0,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 36000
    },
    {
      "Class": "Snow",
      "EquipmentType": "Snow Plow Truck",
      "FleetCount_CVG": 22,
      "TypicalUnitCostUSD": 165000,
      "TypicalHoursPerYear": 220,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 3630000
    },
    {
      "Class": "Snow",
      "EquipmentType": "Deicer Truck",
      "FleetCount_CVG": 16,
      "TypicalUnitCostUSD": 420000,
      "TypicalHoursPerYear": 220,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 6720000
    },
    {
      "Class": "Snow",
      "EquipmentType": "Snow Blower",
      "FleetCount_CVG": 12,
      "TypicalUnitCostUSD": 95000,
      "TypicalHoursPerYear": 220,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 1140000
    },
    {
      "Class": "Snow",
      "EquipmentType": "Runway Broom",
      "FleetCount_CVG": 7,
      "TypicalUnitCostUSD": 280000,
      "TypicalHoursPerYear": 220,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 1960000
    },
    {
      "Class": "Snow",
      "EquipmentType": "Liquid Deice Trailer",
      "FleetCount_CVG": 5,
      "TypicalUnitCostUSD": 38000,
      "TypicalHoursPerYear": 220,
      "PMHoursInterval": 250,
      "DefaultPower": "Diesel",
      "EstReplacementValueUSD": 190000
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Torque Wrench Set",
      "FleetCount_CVG": 14,
      "TypicalUnitCostUSD": 1800,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 25200
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Hydraulic Load Tester",
      "FleetCount_CVG": 6,
      "TypicalUnitCostUSD": 12500,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 75000
    },
    {
      "Class": "Tooling",
      "EquipmentType": "GPU Load Bank",
      "FleetCount_CVG": 5,
      "TypicalUnitCostUSD": 18000,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 90000
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Diagnostic Scan Tool",
      "FleetCount_CVG": 8,
      "TypicalUnitCostUSD": 4500,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 36000
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Battery Load Tester",
      "FleetCount_CVG": 8,
      "TypicalUnitCostUSD": 2200,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 17600
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Tire Bead Breaker / Changer",
      "FleetCount_CVG": 6,
      "TypicalUnitCostUSD": 6800,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 40800
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Alignment / Tracking Gauge",
      "FleetCount_CVG": 5,
      "TypicalUnitCostUSD": 1500,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 7500
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Hose Crimp / Shop Press Kit",
      "FleetCount_CVG": 6,
      "TypicalUnitCostUSD": 3200,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 19200
    },
    {
      "Class": "Tooling",
      "EquipmentType": "Welding / Fabrication Cart",
      "FleetCount_CVG": 6,
      "TypicalUnitCostUSD": 5400,
      "TypicalHoursPerYear": 80,
      "PMHoursInterval": "",
      "DefaultPower": "None",
      "EstReplacementValueUSD": 32400
    }
  ],
  "classTotals": {
    "Power": 949,
    "Non-Power": 2652,
    "Snow": 62,
    "Tooling": 64
  },
  "replacementValue": 112941880,
  "monthly": [
    {
      "month": "2025-10",
      "raised": 59,
      "completed": 60,
      "downtime_hours": 126.7,
      "cost": 14358,
      "preventive": 45,
      "unscheduled": 14,
      "comebacks": 0
    },
    {
      "month": "2025-11",
      "raised": 53,
      "completed": 53,
      "downtime_hours": 159.3,
      "cost": 14292,
      "preventive": 35,
      "unscheduled": 18,
      "comebacks": 1
    },
    {
      "month": "2025-12",
      "raised": 47,
      "completed": 47,
      "downtime_hours": 130,
      "cost": 10421,
      "preventive": 33,
      "unscheduled": 14,
      "comebacks": 0
    },
    {
      "month": "2026-01",
      "raised": 53,
      "completed": 53,
      "downtime_hours": 96.1,
      "cost": 11403,
      "preventive": 35,
      "unscheduled": 18,
      "comebacks": 0
    },
    {
      "month": "2026-02",
      "raised": 44,
      "completed": 44,
      "downtime_hours": 120.6,
      "cost": 14053,
      "preventive": 27,
      "unscheduled": 17,
      "comebacks": 1
    },
    {
      "month": "2026-03",
      "raised": 56,
      "completed": 56,
      "downtime_hours": 151.2,
      "cost": 12316,
      "preventive": 35,
      "unscheduled": 21,
      "comebacks": 0
    },
    {
      "month": "2026-04",
      "raised": 47,
      "completed": 45,
      "downtime_hours": 156.8,
      "cost": 11709,
      "preventive": 29,
      "unscheduled": 18,
      "comebacks": 0
    },
    {
      "month": "2026-05",
      "raised": 51,
      "completed": 51,
      "downtime_hours": 149,
      "cost": 10620,
      "preventive": 38,
      "unscheduled": 13,
      "comebacks": 0
    },
    {
      "month": "2026-06",
      "raised": 61,
      "completed": 61,
      "downtime_hours": 176.4,
      "cost": 16778,
      "preventive": 33,
      "unscheduled": 28,
      "comebacks": 0
    },
    {
      "month": "2026-07",
      "raised": 53,
      "completed": 55,
      "downtime_hours": 181.2,
      "cost": 14883,
      "preventive": 34,
      "unscheduled": 19,
      "comebacks": 0
    },
    {
      "month": "2026-08",
      "raised": 55,
      "completed": 54,
      "downtime_hours": 150.8,
      "cost": 16577,
      "preventive": 39,
      "unscheduled": 16,
      "comebacks": 0
    },
    {
      "month": "2026-09",
      "raised": 19,
      "completed": 11,
      "downtime_hours": 52.5,
      "cost": 5766,
      "preventive": 17,
      "unscheduled": 2,
      "comebacks": 0
    }
  ]
}
