// GENERATED by scripts/import-dhl-gse-workbook.mjs — do not edit by hand.
// Source: data-source/DHL_CVG_GSE_5Year_CMMS_Demo.xlsx (07_PM_Standards)
//
// Synthetic, operationally patterned demo data — not DHL actuals. Values are the
// sheet's own. Dates are stored exactly as supplied; the shift that keeps the
// demo current happens at read time in ./index.js.

export const PM_STANDARDS = [
  {"TemplateID":"PM-PREUSE","Description":"Daily / pre-use operator check","Trigger":"Calendar","Interval":1,"StdHours":0.15,"DefaultCraft":"Operator","AppliesTo":"All in-service powered + selected non-power"},
  {"TemplateID":"PM-7D","Description":"Lights, horn, backup alarm, walkaround","Trigger":"Calendar","Interval":7,"StdHours":0.4,"DefaultCraft":"Technician","AppliesTo":"Powered GSE"},
  {"TemplateID":"PM-14D","Description":"Tire pressure, tread, lug torque","Trigger":"Calendar","Interval":14,"StdHours":0.5,"DefaultCraft":"Technician","AppliesTo":"Wheeled GSE"},
  {"TemplateID":"PM-30D","Description":"30-day operational inspection","Trigger":"Calendar","Interval":30,"StdHours":1.5,"DefaultCraft":"Technician","AppliesTo":"Powered GSE + loaders"},
  {"TemplateID":"PM-60D","Description":"Brake pad thickness and function","Trigger":"Calendar","Interval":60,"StdHours":1.2,"DefaultCraft":"Technician","AppliesTo":"Tractors, loaders, trucks"},
  {"TemplateID":"PM-90D","Description":"Battery and charging load test","Trigger":"Calendar","Interval":90,"StdHours":1,"DefaultCraft":"Technician","AppliesTo":"Electric + starting batteries"},
  {"TemplateID":"PM-250H","Description":"250-hour engine / drivetrain service","Trigger":"Hours","Interval":250,"StdHours":3.5,"DefaultCraft":"Technician","AppliesTo":"Diesel/LPG/gasoline powered"},
  {"TemplateID":"PM-500H","Description":"500-hour major service / transmission","Trigger":"Hours","Interval":500,"StdHours":6,"DefaultCraft":"Lead Technician","AppliesTo":"Pushback, loaders, tractors"},
  {"TemplateID":"PM-ANN","Description":"Annual DOT + IATA AHM / OEM inspection","Trigger":"Calendar","Interval":365,"StdHours":8,"DefaultCraft":"Lead Technician","AppliesTo":"All registered GSE"},
  {"TemplateID":"PM-SEAS-IN","Description":"Snow season prepare-in","Trigger":"Seasonal","Interval":365,"StdHours":4,"DefaultCraft":"Technician","AppliesTo":"Snow fleet"},
  {"TemplateID":"PM-SEAS-OUT","Description":"Snow season store / flush","Trigger":"Seasonal","Interval":365,"StdHours":3,"DefaultCraft":"Technician","AppliesTo":"Snow fleet"},
  {"TemplateID":"Internal averages used as the expectation (demo)","Description":"","Trigger":"","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Metric","Description":"Internal standard","Trigger":"Source","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"250-hr PM compliance (completed within 10% of due hours)","Description":"≥ 92%","Trigger":"GSE reliability playbook","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Annual inspection on-time","Description":"100% of registered units","Trigger":"Airline / airport audit","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Come-back rate (unscheduled, 30-day)","Description":"≤ 10%","Trigger":"Quality KPI","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Mean time to return-to-service P1","Description":"≤ 2.5 hours","Trigger":"Ramp control SLA","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Wrench time (recorded / scheduled)","Description":"≥ 65%","Trigger":"Labor KPI","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Cycle-count absolute variance","Description":"≤ 2.5% of counted value","Trigger":"Inventory audit control","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""},
  {"TemplateID":"Same-part reinstall inside 45% of typical life","Description":"Flag + warranty review","Trigger":"Parts metrics","Interval":"","StdHours":"","DefaultCraft":"","AppliesTo":""}
]
