// Chiller AI — predictive maintenance and refrigerant leak detection.
//
// Built from the solution overview prepared for AbbVie: continuous monitoring
// of chiller refrigeration, thermal, electrical and operating parameters, so a
// facility team moves from reactive troubleshooting to condition-based work.
//
// The whole point of a pack is that only the inputs change. The 126 assets and
// 84 work orders below are generated by the same code that generates the
// generic pack's — swapping to this one turns the plant into a chiller estate
// without a line changing in any of the 56 screens.

export default {
  key: 'chiller',
  label: 'Chiller AI — predictive maintenance',

  org: {
    organization_name: 'AbbVie',
    organization_code: 'ABV',
    industry: 'Pharmaceutical manufacturing',
    address: '1 North Waukegan Road',
    city: 'North Chicago',
    country: 'United States',
    timezone: 'America/Chicago',
    currency: 'USD',
    currency_symbol: '$',
  },

  user: {
    name: 'Kenneth Lawrence',
    email: 'kenneth.lawrence@abbvie.example',
    mobile: '+1 847 555 0142',
    role_name: 'Facilities Reliability Lead',
    initials: 'KL',
  },

  sites: [
    { site_id: 'site_01', site_name: 'North Chicago Campus', code: 'NCH', city: 'North Chicago', country: 'United States', is_default: true },
    { site_id: 'site_02', site_name: 'Worcester Biologics', code: 'WOR', city: 'Worcester', country: 'United States', is_default: false },
    { site_id: 'site_03', site_name: 'Barceloneta Plant', code: 'BAR', city: 'Barceloneta', country: 'Puerto Rico', is_default: false },
  ],

  locations: [
    { functional_location_id: 'loc_01', name: 'Central Utility Plant', site_id: 'site_01', parent_id: null, level: 1 },
    { functional_location_id: 'loc_02', name: 'Chiller Hall A', site_id: 'site_01', parent_id: 'loc_01', level: 2 },
    { functional_location_id: 'loc_03', name: 'Chiller Hall B', site_id: 'site_01', parent_id: 'loc_01', level: 2 },
    { functional_location_id: 'loc_04', name: 'Cooling Tower Yard', site_id: 'site_01', parent_id: 'loc_01', level: 2 },
    { functional_location_id: 'loc_05', name: 'Process Cooling — Biologics', site_id: 'site_02', parent_id: null, level: 1 },
    { functional_location_id: 'loc_07', name: 'Clean Utilities', site_id: 'site_02', parent_id: null, level: 1 },
    { functional_location_id: 'loc_08', name: 'Fill Finish AHUs', site_id: 'site_02', parent_id: 'loc_05', level: 2 },
    { functional_location_id: 'loc_06', name: 'Utility Building', site_id: 'site_03', parent_id: null, level: 1 },
    { functional_location_id: 'loc_09', name: 'Chiller Plant', site_id: 'site_03', parent_id: 'loc_06', level: 2 },
    { functional_location_id: 'loc_10', name: 'API Process Cooling', site_id: 'site_03', parent_id: null, level: 1 },
  ],

  assetCount: 126,
  assetKinds: [
    'Centrifugal Chiller', 'Screw Chiller', 'Absorption Chiller', 'Cooling Tower',
    'CHW Pump', 'Condenser Water Pump', 'Air Handling Unit', 'Purge Unit',
    'Dry Cooler', 'Refrigerant Monitor',
  ],
  makers: ['Trane', 'Carrier', 'York', 'Daikin', 'Smardt', 'McQuay'],

  workOrderCount: 84,
  // The failure modes the overview names, written as a technician would raise
  // them rather than as analytics output.
  tasks: [
    'Evaporator superheat rising — check charge and expansion valve',
    'Condenser subcooling falling against load — suspect refrigerant loss',
    'Leak test condenser barrel and flanges',
    'Compressor short-cycling outside expected load band',
    'Approach temperature drift — inspect and clean condenser tubes',
    'COP below baseline at matched load and ambient',
    'Recover, evacuate and recharge to nameplate',
    'Replace filter drier and sample oil for acid',
    'Purge unit running excessively — check for non-condensables',
    'Calibrate suction and discharge pressure transducers',
  ],

  partCount: 48,
  partNames: [
    'R-134a Refrigerant 30 lb', 'R-513A Refrigerant 25 lb', 'Filter Drier Core',
    'POE Compressor Oil ISO 68', 'Shaft Seal Kit', 'Pressure Transducer 0-500 psi',
    'Suction Temperature RTD', 'Electronic Expansion Valve', 'Purge Unit Filter',
    'Condenser Tube Brush Kit', 'Vibration Isolator', 'Flow Switch',
  ],

  technicians: [
    { user_id: 'usr_t01', name: 'Daniel Reeve', role: 'Technician', trade: 'Refrigeration' },
    { user_id: 'usr_t02', name: 'Tom Whelan', role: 'Technician', trade: 'Electrical' },
    { user_id: 'usr_t03', name: 'Sara Kovac', role: 'Technician', trade: 'Controls' },
    { user_id: 'usr_t04', name: 'Marcus Bell', role: 'Supervisor', trade: 'Refrigeration' },
    { user_id: 'usr_t05', name: 'Ellie Brandt', role: 'Technician', trade: 'Electrical' },
    { user_id: 'usr_t06', name: 'Owen Marsh', role: 'Technician', trade: 'Mechanical' },
    { user_id: 'usr_t07', name: 'Grace Holloway', role: 'Planner', trade: 'Planning' },
    { user_id: 'usr_t08', name: 'Victor Lang', role: 'Technician', trade: 'Controls' },
  ],

  vendorNames: [
    'Trane Service', 'Carrier Commercial Service', 'Johnson Controls',
    'Hudson Technologies', 'Airgas Refrigerants', 'Grainger',
    'Motion Industries', 'Applied Industrial',
  ],

  // The specialised module. Present here and absent from the generic pack, so
  // Condition Monitoring only appears in the menu for demos that have it.
  domain: {
    key: 'chiller',
    label: 'Chiller AI',
    subtitle: 'Refrigerant leak detection and efficiency drift',

    // The menu group this module contributes. It used to be written into
    // nav.jsx, which meant the nav switched the group on for any pack that had
    // a domain and then showed that pack a menu of chiller screens. A module
    // names its own sections; `icon` and each child's `key` index the ICONS map
    // in nav.jsx, because icons are JSX and a pack is plain data.
    icon: 'chiller',
    sections: [
      { key: 'chiller-overview', label: 'Fleet Overview', kw: 'chiller fleet overview health leak risk efficiency alerts monitoring dashboard refrigerant' },
      { key: 'chiller-monitor', label: 'Condition Monitoring', kw: 'condition monitoring superheat subcooling suction discharge pressure approach compressor current cop chilled water parameter trend sparkline' },
      { key: 'leak-detection', label: 'Leak Detection', kw: 'refrigerant leak detection probability risk score subcooling charge loss top up inspection r134a r513a' },
      { key: 'chiller-efficiency', label: 'Efficiency & Energy', kw: 'cop coefficient of performance efficiency drift energy kw per ton approach load baseline cost' },
      { key: 'chiller-solution', label: 'Solution Overview', kw: 'solution overview architecture bms plc bacnet modbus opc ua mqtt sensors data sources roadmap phases benefits use cases' },
    ],

    // Only these asset types carry refrigerant, so only these get scored. A
    // leak-risk figure against a pump is the kind of detail that loses a room.
    monitoredKinds: ['Centrifugal Chiller', 'Screw Chiller', 'Absorption Chiller'],

    // The monitored parameters, with the ranges the analytics judge against.
    // Ranges are the ones an operating chiller actually sits in — a screen that
    // flags healthy plant is worse than one that flags nothing.
    parameters: [
      { key: 'superheat', label: 'Evaporator superheat', unit: '°F', normal: [8, 12], warn: [12, 16], source: 'Chiller controller', meaning: 'Rising superheat points to insufficient refrigerant flow or a falling charge.' },
      { key: 'subcooling', label: 'Condenser subcooling', unit: '°F', normal: [10, 15], warn: [6, 10], invert: true, source: 'Chiller controller', meaning: 'Subcooling falling against steady load is the clearest early sign of refrigerant loss.' },
      { key: 'suction_pressure', label: 'Suction pressure', unit: 'psi', normal: [58, 72], warn: [50, 58], invert: true, source: 'Pressure transducer', meaning: 'Compared against load-normalised expectation, not a fixed setpoint.' },
      { key: 'discharge_pressure', label: 'Discharge pressure', unit: 'psi', normal: [180, 235], warn: [235, 265], source: 'Pressure transducer', meaning: 'High discharge with a clean condenser suggests non-condensables.' },
      { key: 'approach', label: 'Condenser approach', unit: '°F', normal: [1.5, 3.5], warn: [3.5, 5.5], source: 'RTD pair', meaning: 'Approach widening is fouling or tube scaling before it is anything else.' },
      { key: 'compressor_current', label: 'Compressor current', unit: 'A', normal: [180, 320], warn: [320, 380], source: 'Current transformer', meaning: 'Read with runtime and cycling, not on its own.' },
      { key: 'cop', label: 'Coefficient of performance', unit: '', normal: [5.2, 6.8], warn: [4.4, 5.2], invert: true, source: 'Derived', meaning: 'Efficiency drift shows here before it shows on a bill.' },
      { key: 'chw_supply', label: 'Chilled water supply', unit: '°F', normal: [42, 45], warn: [45, 48], source: 'RTD', meaning: 'Leaving water temperature against setpoint.' },
    ],

    // What the platform is made of, from the overview's four layers.
    architecture: [
      { n: 1, title: 'Equipment Layer', body: 'Chillers, compressors, pumps, sensors, OEM controllers and existing instrumentation.' },
      { n: 2, title: 'Connectivity Layer', body: 'BMS and PLC integration and IoT gateways over BACnet, Modbus, OPC UA or MQTT.' },
      { n: 3, title: 'AI & Analytics Layer', body: 'Baseline learning, anomaly detection, leak-risk scoring, asset health analytics and trend analysis.' },
      { n: 4, title: 'Maintenance Layer', body: 'Dashboards, alarms, inspections, work orders, technician actions, history and management reporting.' },
    ],

    // The sensor and data-source table, kept so the site audit conversation has
    // something concrete to point at.
    dataSources: [
      ['Refrigerant temperature', 'Temperature sensors / existing chiller controller'],
      ['Suction & discharge pressure', 'Pressure transducers'],
      ['Chilled / condenser water temperatures', 'RTD / temperature sensors'],
      ['Compressor current / power', 'Current transformer / power meter'],
      ['Vibration', 'Industrial vibration sensor'],
      ['Flow / differential pressure', 'Flow meter / differential pressure sensor'],
      ['Valve position / compressor state', 'Chiller PLC or BMS point'],
      ['Ambient temperature & humidity', 'Environmental sensor'],
    ],

    roadmap: [
      { phase: 'Phase 1', title: 'Site Assessment', body: 'Inventory, BMS points, history, sensor gaps, connectivity.' },
      { phase: 'Phase 2', title: 'Pilot Monitoring', body: 'Connect selected chillers, baseline data, dashboards, alerts.' },
      { phase: 'Phase 3', title: 'AI Tuning & Workflow', body: 'Tune thresholds, validate indicators, connect work-order workflows.' },
      { phase: 'Phase 4', title: 'Scale & Optimise', body: 'Scale to more chillers and sites, and refine fleet KPIs.' },
    ],

    useCases: [
      'Refrigerant leak probability scoring using multi-parameter anomaly detection.',
      'Early warning for efficiency degradation and abnormal COP trends.',
      'Compressor fault and abnormal cycling detection.',
      'Chiller health scoring and risk ranking for maintenance prioritisation.',
      'Predictive alerts with likely cause, affected asset, severity and recommended inspection action.',
    ],

    refrigerants: ['R-134a', 'R-513A', 'R-1233zd'],
  },
}
