'use client'

// Work requests — what the floor asked for, before a planner touched it.
//
// The customer listed "unlimited work orders" and "unlimited work order
// requests" as two separate interests, so this is its own screen. But the
// workbook has one table, not two: every row carries a `Requested By`, and the
// requests are the rows raised by an operator, a shift lead or a safety officer
// rather than generated by the PM system.
//
// So this screen is a real view over the same records rather than a second
// dataset. That is also how the product works — a request becomes a work order
// when it is accepted, it does not get copied into a different table — and
// inventing a separate requests register would have demonstrated a workflow the
// platform does not have.

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Section, DataTable, Toolbar, StatusBadge, Priority } from '../lib/kit'
import PageHeading from '../components/PageHeading'
import { StatCards } from '../components/MetricCard'
import { Ref, DeptChip, TwoLine, DueDate, Note, Bars } from '../components/cells'
import { useDept } from '../lib/deptStore'
import { workOrders } from '../lib/data'

// The PM system raises its own work; everything else came from a person.
const SYSTEM_REQUESTER = 'PM System'

export default function Requests() {
  const router = useRouter()
  const { scope, deptName } = useDept()
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('all')
  const [origin, setOrigin] = useState('Raised by a person')

  const all = useMemo(() => scope(workOrders), [scope])

  const requests = all.filter((w) => w.requestedBy !== SYSTEM_REQUESTER)
  const systemRaised = all.filter((w) => w.requestedBy === SYSTEM_REQUESTER)

  const base = origin === 'Raised by a person' ? requests
    : origin === 'Raised by the PM system' ? systemRaised
      : all

  const rows = useMemo(() => {
    const q = search.trim().toLowerCase()
    return base.filter((w) => (
      (status === 'all' || w.status === status) &&
      (!q || [w.woNo, w.title, w.requestedBy, w._assetName, w.description].join(' ').toLowerCase().includes(q))
    ))
  }, [base, search, status])

  const awaiting = requests.filter((w) => w.assignedTo === 'Unassigned' && w._open)
  const requesters = [...new Set(requests.map((w) => w.requestedBy))].filter(Boolean)

  return (
    <div>
      <PageHeading
        title="Request Maintenance"
        subtitle={`What the floor reported and who reported it, before a planner assigned it. ${deptName}.`}
      />

      <StatCards items={[
        { label: 'Raised by a person', value: requests.length, note: `${requesters.length} distinct requesters`, icon: 'list' },
        { label: 'Awaiting a planner', value: awaiting.length, tone: awaiting.length ? 'warning' : 'success', note: 'Open and unassigned', icon: 'clock' },
        { label: 'Accepted & assigned', value: requests.filter((w) => w.assignedTo !== 'Unassigned').length, tone: 'success', note: 'Now owned by a technician', icon: 'tick' },
        { label: 'Raised by the PM system', value: systemRaised.length, note: 'Generated from a schedule' },
        { label: 'Total records', value: all.length, note: 'One table, two views' },
      ]} />

      <Note>
        Requests and work orders are the same records in this product. A row becomes a work
        order when a planner accepts and assigns it — it is not copied into a second table, so
        nothing can drift between the two.
      </Note>

      <Section title="Request queue">
        <Toolbar
          search={search} onSearch={setSearch}
          placeholder="Search request, requester or asset…"
          filters={[
            { label: 'Origin', value: origin, onChange: setOrigin, options: ['Raised by a person', 'Raised by the PM system', 'Everything'] },
            { label: 'Status', value: status, onChange: setStatus, options: [...new Set(all.map((w) => w.status))] },
          ]}
        />

        <DataTable
          rows={rows}
          pageSize={15}
          onRowClick={(w) => router.push(`/portal/dna/work-orders/${w.woNo}`)}
          empty="No requests match these filters."
          columns={[
            { key: 'woNo', label: 'Ref', width: 96, render: (w) => <Ref>{w.woNo}</Ref> },
            { key: 'title', label: 'Reported', render: (w) => <TwoLine top={w.title} bottom={w.description} /> },
            {
              key: 'requestedBy', label: 'Requested by', width: 168,
              render: (w) => (w.requestedBy === SYSTEM_REQUESTER
                ? <span style={{ fontSize: 11.5, color: '#6d28d9', fontWeight: 700 }}>{w.requestedBy}</span>
                : <span style={{ fontSize: 12 }}>{w.requestedBy}</span>),
            },
            { key: 'locationCode', label: 'Dept', width: 76, render: (w) => <DeptChip code={w.locationCode} name={w._locationName} /> },
            { key: 'priority', label: 'Priority', width: 100, render: (w) => <Priority value={w.priority} /> },
            { key: 'dateRequested', label: 'Raised', width: 118, render: (w) => <DueDate value={w.dateRequested} days={null} done /> },
            {
              key: 'assignedTo', label: 'Owner', width: 132,
              render: (w) => (w.assignedTo === 'Unassigned'
                ? <span style={{ color: '#b45309', fontWeight: 700, fontSize: 11.5 }}>Awaiting planner</span>
                : <span style={{ fontSize: 12 }}>{w.assignedTo}</span>),
            },
            { key: 'status', label: 'Status', width: 112, render: (w) => <StatusBadge>{w.status}</StatusBadge> },
          ]}
        />
      </Section>

      <Section title="Who reports the most">
        <Bars
          data={requesters
            .map((r) => ({ name: r, value: requests.filter((w) => w.requestedBy === r).length }))
            .sort((a, b) => b.value - a.value)}
        />
      </Section>
    </div>
  )
}
