// The tyre industry's reliability library.
//
// Kept apart from any one pack because the analysis is not the plant's — it is
// the industry's. A radial tyre plant's Banbury mixer fails the same four ways
// in Chennai as in Ohio, and the library is worth carrying in every build so a
// reliability conversation can be had on whichever portal is already open,
// without standing up a demo container for it.
//
// A pack for a tyre plant attaches it to its own estate (lib/packs/tyre-plant);
// on any other build it is a reference library, and the screen says so.
// ── the reliability analysis ────────────────────────────────────────────
//
// Read it as RCM reads: what is this machine for (`fn`), how does that
// purpose fail (`ff`), by what mechanism (`mode`), what happens then — to the
// plant (`effect`) and to the tyre (`product`) — and what class of
// consequence that is. The consequence decides the task, which is why it is
// recorded per mode and not inferred from a score.
//
//   Safety       — can hurt somebody.
//   Environment  — breaches a consent or releases something.
//   Production   — costs output or scrap, and nothing worse.
//   Hidden       — nobody finds out until the protected thing is needed. A
//                  relief valve that will not lift, an interlock that will
//                  not trip, a gauge that reads right when it is wrong. These
//                  are answered by a failure-finding test, never by watching.
//
// `signal` is the tag a PLC or condition monitor already carries, where one
// exists; it is what makes a mode detectable in advance rather than at the
// moment it stops the line. `pf` is the P-F interval in days — the warning a
// watched mode gives — and it is what sets a sensible inspection interval:
// check at half of it, or the warning is missed between checks.
//
// `severity` and `likelihood` are the analysis's own starting values. The
// engine raises likelihood where the work order history actually shows
// breakdowns on that unit, so the screen cannot claim a mode is rare on a
// machine that has failed on it twice this year.

const library = {
  basis: 'RCM analysis for a radial tyre plant — industry failure modes mapped to this estate. '
    + 'The plant is illustrative; the equipment, functions and failure modes are the industry’s.',
  stages: [
    { key: 'mixing', label: 'Mixing' },
    { key: 'extrusion', label: 'Extrusion' },
    { key: 'calendering', label: 'Calendering' },
    { key: 'components', label: 'Component preparation' },
    { key: 'building', label: 'Tyre building' },
    { key: 'curing', label: 'Curing' },
    { key: 'finishing', label: 'Finishing & inspection' },
    { key: 'utilities', label: 'Utilities' },
  ],

  equipment: [
    {
      kind: 'Banbury Internal Mixer',
      stopHours: 8,
      stage: 'mixing',
      criticality: 'High',
      purpose: 'Disperse fillers and chemicals into rubber to a specified compound within the batch cycle.',
      modes: [
        {
          fn: 'Mix each batch to specification within the cycle time',
          ff: 'Batch leaves the mixer out of specification',
          mode: 'Rotor tip wear beyond clearance limit',
          effect: 'Dispersion falls away, cycle lengthens, energy per batch climbs',
          product: 'Compound viscosity and filler dispersion out of range — carried into every component made from it',
          consequence: 'Production', severity: 8, likelihood: 5,
          detection: 'Energy per batch and Mooney viscosity trend; tip clearance measured at shutdown',
          signal: 'Rotor drive kWh per batch',
          task: 'Trend energy per batch; measure tip clearance at each shutdown and rebuild tips at the limit',
          interval: 'Trend weekly · measure 6-monthly', pf: 60,
        },
        {
          fn: 'Contain the batch in the mixing chamber',
          ff: 'Compound escapes at the rotor shaft',
          mode: 'Dust stop seal wear or failure',
          effect: 'Compound and filler escape to the pit; seal ring and shaft damage if run on',
          product: 'Batch weight short and contaminated with seal debris',
          consequence: 'Environment', severity: 7, likelihood: 6,
          detection: 'Seal air pressure and grease consumption; visual at the shaft each shift',
          signal: 'Seal air pressure (bar)',
          task: 'Seal air pressure check each shift; replace seal rings on condition',
          interval: 'Each shift · replace on condition', pf: 21,
        },
        {
          fn: 'Hold ram pressure on the batch throughout mixing',
          ff: 'Ram pressure is not maintained',
          mode: 'Ram cylinder seal leak or air supply drift',
          effect: 'Ram floats, mixing energy varies batch to batch',
          product: 'Batch-to-batch variation in cure rate — seen later as scorch or under-cure',
          consequence: 'Production', severity: 7, likelihood: 5,
          detection: 'Ram position and pressure trace compared against the recipe',
          signal: 'Ram cylinder pressure (bar) and position (mm)',
          task: 'Compare the ram trace against the recipe on every shift start; reseal on drift',
          interval: 'Each shift', pf: 14,
        },
        {
          fn: 'Discharge the batch when the cycle completes',
          ff: 'The drop door does not open or does not seal',
          mode: 'Drop door hydraulic or latch failure',
          effect: 'Batch held in the chamber and scorched, or leaks during mixing; line stops',
          product: 'Whole batch scrapped',
          consequence: 'Production', severity: 8, likelihood: 4,
          detection: 'Door open/close time from the PLC; latch wear at inspection',
          signal: 'Drop door cycle time (s)',
          task: 'Trend door cycle time; inspect latch and liner plates monthly',
          interval: 'Monthly', pf: 30,
        },
        {
          fn: 'Hold chamber temperature within the mixing window',
          ff: 'Chamber temperature is not controlled',
          mode: 'Temperature control unit circuit fouling or valve failure',
          effect: 'Cooling water flow falls, compound temperature runs away',
          product: 'Scorched compound — the batch and anything already made from it',
          consequence: 'Production', severity: 9, likelihood: 4,
          detection: 'Water in/out delta-T and flow against batch temperature',
          signal: 'TCU water ΔT (°C) and flow (m³/h)',
          task: 'Trend ΔT and flow; descale and prove the control valve at each planned shutdown',
          interval: 'Trend daily · clean 6-monthly', pf: 30,
        },
        {
          fn: 'Transmit drive torque to the rotors',
          ff: 'The drive train cannot carry the torque',
          mode: 'Mixer gearbox bearing or gear tooth wear',
          effect: 'Weeks of warning on vibration and oil debris, then a stop that takes the line out for days',
          product: 'No output from the whole mixing line while it is down',
          consequence: 'Production', severity: 10, likelihood: 3,
          detection: 'Vibration spectrum and quarterly oil analysis for wear metals',
          signal: 'Gearbox vibration (mm/s RMS) and oil particle count',
          task: 'Vibration route monthly; oil sample quarterly; replace bearings on the trend',
          interval: 'Monthly · oil quarterly', pf: 120,
        },
      ],
    },

    {
      kind: 'Two-Roll Mill',
      stopHours: 4,
      stage: 'mixing',
      criticality: 'High',
      purpose: 'Sheet and cool the discharged batch, and feed it forward at an even gauge.',
      modes: [
        {
          fn: 'Sheet the compound at an even gauge across the roll face',
          ff: 'Gauge varies across the sheet',
          mode: 'Roll bearing wear or nip adjustment backlash',
          effect: 'Nip opens under load; gauge wanders across the face',
          product: 'Downstream component weight varies — tread gauge and tyre weight out of tolerance',
          consequence: 'Production', severity: 7, likelihood: 5,
          detection: 'Nip gap measurement and bearing vibration',
          signal: 'Roll bearing vibration (mm/s) and nip position (mm)',
          task: 'Verify nip gap weekly; vibration route monthly; reset backlash on drift',
          interval: 'Weekly', pf: 45,
        },
        {
          fn: 'Hold the roll surface temperature',
          ff: 'Roll temperature is not held',
          mode: 'Roll cooling water leak or rotary union failure',
          effect: 'Roll runs hot, compound sticks and bags on the roll',
          product: 'Scorch and tack loss in the sheet',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Roll surface temperature and water flow',
          signal: 'Roll surface temperature (°C)',
          task: 'Infrared roll survey weekly; rebuild rotary unions on condition',
          interval: 'Weekly', pf: 21,
        },
        {
          fn: 'Stop both rolls within the safety distance when the trip bar is struck',
          ff: 'The mill does not stop when the trip bar is operated',
          mode: 'Safety trip bar or brake failure — discovered only when it is needed',
          effect: 'Nothing, until an operator is at the nip and the trip is used',
          product: 'None — this one is about the person at the machine',
          consequence: 'Hidden', severity: 10, likelihood: 3,
          detection: 'Not detectable in service; found only by testing it',
          signal: '',
          task: 'Function-test the trip bar and measure stopping distance against the standard',
          interval: 'Weekly test', pf: 0,
        },
      ],
    },

    {
      kind: 'Batch-Off Cooling Line',
      stopHours: 3,
      stage: 'mixing',
      criticality: 'Medium',
      purpose: 'Cool, coat and stack the milled sheet so it can be stored without blocking.',
      modes: [
        {
          fn: 'Carry the sheet through the line without stretching it',
          ff: 'The sheet is stretched or torn in transit',
          mode: 'Festoon roller seized or tracking out',
          effect: 'Tension spikes, sheet necks or tears, line stops to re-thread',
          product: 'Sheet gauge pulled thin — component weight low',
          consequence: 'Production', severity: 5, likelihood: 6,
          detection: 'Festoon position trace and roller rotation check',
          signal: 'Festoon position (%)',
          task: 'Walk the line weekly for non-rotating rollers; replace bearings on condition',
          interval: 'Weekly', pf: 21,
        },
        {
          fn: 'Coat the sheet so stacked slabs separate',
          ff: 'Slabs block together in storage',
          mode: 'Dip tank concentration drift or spray nozzle blockage',
          effect: 'Under-coated sheet; slabs weld together in the rack',
          product: 'Compound unusable without re-milling — age and scorch risk',
          consequence: 'Production', severity: 6, likelihood: 6,
          detection: 'Tank concentration test and nozzle pattern check',
          signal: 'Dip tank concentration (%)',
          task: 'Test concentration each shift; clean nozzles weekly',
          interval: 'Each shift', pf: 7,
        },
        {
          fn: 'Dry the sheet before stacking',
          ff: 'Sheet reaches the stacker wet',
          mode: 'Drying fan or heater failure',
          effect: 'Wet slabs stick; stacker jams',
          product: 'Moisture carried into the compound — porosity at cure',
          consequence: 'Production', severity: 6, likelihood: 4,
          detection: 'Fan current and air temperature at the exit',
          signal: 'Exit air temperature (°C)',
          task: 'Trend exit temperature; clean and balance fans quarterly',
          interval: 'Quarterly', pf: 30,
        },
      ],
    },

    {
      kind: 'Tread Extruder',
      stopHours: 6,
      stage: 'extrusion',
      criticality: 'High',
      purpose: 'Extrude tread and sidewall profiles to gauge and weight at line speed.',
      modes: [
        {
          fn: 'Deliver compound at a steady output and pressure',
          ff: 'Output falls or surges at the head',
          mode: 'Screw and barrel wear — clearance opened up',
          effect: 'Output per rev falls, head pressure drops, speed has to be pushed to hold rate',
          product: 'Tread gauge and weight drift — caught at final weight check, often after hours of production',
          consequence: 'Production', severity: 8, likelihood: 5,
          detection: 'Output per screw rev and head pressure trend; clearance measured at strip-down',
          signal: 'Head pressure (bar) and screw speed (rpm) against output (kg/h)',
          task: 'Trend output per rev weekly; measure screw and barrel clearance at each planned strip-down',
          interval: 'Weekly trend · annual measurement', pf: 90,
        },
        {
          fn: 'Hold each barrel zone at its set temperature',
          ff: 'A zone runs off its set point',
          mode: 'Heater band burnout or thermocouple drift',
          effect: 'Zone runs cold or hot without the operator seeing it if the sensor is the one that drifted',
          product: 'Scorch, or poor knitting and porosity in the extrudate',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'Zone deviation alarms and thermal survey; drift is only found by calibration',
          signal: 'Zone temperature deviation (°C)',
          task: 'Thermal survey monthly; calibrate thermocouples against a reference 6-monthly',
          interval: 'Monthly · calibrate 6-monthly', pf: 30,
        },
        {
          fn: 'Feed the extruder evenly',
          ff: 'Feed to the screw is uneven',
          mode: 'Feed roll drive fault or worn feed roll',
          effect: 'Surging output, pressure oscillation',
          product: 'Gauge ripple down the length of the tread',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Head pressure oscillation and feed roll current',
          signal: 'Feed roll motor current (A)',
          task: 'Trend pressure oscillation; inspect feed roll surface quarterly',
          interval: 'Quarterly', pf: 30,
        },
        {
          fn: 'Stop the extruder before head pressure reaches the design limit',
          ff: 'Over-pressure protection does not act',
          mode: 'Head pressure transducer or trip circuit failed — not visible in normal running',
          effect: 'None until a blockage raises pressure; then a burst rupture disc or worse',
          product: 'None directly — this protects the machine and the people beside it',
          consequence: 'Hidden', severity: 9, likelihood: 3,
          detection: 'Found only by testing the trip against an injected signal',
          signal: '',
          task: 'Function-test the over-pressure trip with a simulated signal; verify the rupture disc rating',
          interval: '6-monthly test', pf: 0,
        },
      ],
    },

    {
      kind: 'Extruder Gear Pump & Screen Changer',
      stopHours: 3,
      stage: 'extrusion',
      criticality: 'High',
      purpose: 'Meter compound at constant pressure and filter contamination before the die.',
      modes: [
        {
          fn: 'Meter compound at a constant pressure to the die',
          ff: 'Delivery pressure is not constant',
          mode: 'Gear pump wear or shaft seal leak',
          effect: 'Pressure sags, compound leaks at the seal, output falls',
          product: 'Gauge variation along the profile',
          consequence: 'Production', severity: 7, likelihood: 4,
          detection: 'Inlet-to-outlet pressure ratio and visible leakage',
          signal: 'Pump inlet/outlet pressure (bar)',
          task: 'Trend the pressure ratio; reseal or rebuild on the trend',
          interval: 'Weekly trend', pf: 60,
        },
        {
          fn: 'Filter contamination out of the melt stream',
          ff: 'Contamination passes to the die',
          mode: 'Screen pack blinded, or changer sealing face worn so melt bypasses the pack',
          effect: 'Pressure climbs before the pack; bypass sends contamination straight through',
          product: 'Hard specks and cord damage in the component — a scrap tyre at inspection or, worse, in service',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'Differential pressure across the pack; sealing face inspected at changeover',
          signal: 'Screen ΔP (bar)',
          task: 'Change the pack on ΔP rather than on time; lap the sealing faces at each pack change',
          interval: 'On ΔP limit', pf: 10,
        },
        {
          fn: 'Change the screen pack without stopping the line',
          ff: 'The changer will not index',
          mode: 'Changer hydraulic drift or valve sticking',
          effect: 'Pack change becomes a line stop',
          product: 'Extrudate lost through the change',
          consequence: 'Production', severity: 5, likelihood: 4,
          detection: 'Index time from the PLC and hydraulic oil cleanliness',
          signal: 'Changer index time (s)',
          task: 'Trend index time; sample hydraulic oil quarterly',
          interval: 'Quarterly', pf: 45,
        },
      ],
    },

    {
      kind: 'Four-Roll Calender',
      stopHours: 10,
      stage: 'calendering',
      criticality: 'High',
      purpose: 'Coat steel cord and fabric with rubber to a controlled gauge across the full web.',
      modes: [
        {
          fn: 'Hold sheet gauge across the width of the web',
          ff: 'Gauge varies across or along the web',
          mode: 'Roll bearing wear or crown adjustment actuator drift',
          effect: 'Roll deflection changes under load; profile goes out across the face',
          product: 'Coated ply gauge out of tolerance — belt edge and endurance problems in the finished tyre',
          consequence: 'Production', severity: 9, likelihood: 4,
          detection: 'On-line gauge profile, bearing vibration and crown actuator position',
          signal: 'Beta gauge profile (mm) and roll bearing vibration (mm/s)',
          task: 'Watch the profile trace every shift; vibration route monthly; regrind or rebearing on the trend',
          interval: 'Each shift · vibration monthly', pf: 90,
        },
        {
          fn: 'Hold roll surface temperature within the coating window',
          ff: 'Roll temperature drifts from set point',
          mode: 'Rotary union leak or TCU control valve failure',
          effect: 'Coating temperature moves; compound sticks or fails to penetrate the cord',
          product: 'Poor rubber-to-cord penetration — the cause of later belt separation',
          consequence: 'Production', severity: 9, likelihood: 4,
          detection: 'Surface temperature survey against set point',
          signal: 'Roll surface temperature (°C)',
          task: 'Infrared survey weekly; service rotary unions annually',
          interval: 'Weekly', pf: 30,
        },
        {
          fn: 'Keep the roll face clean',
          ff: 'Compound builds up on the roll',
          mode: 'Doctor blade worn or incorrectly loaded',
          effect: 'Build-up transfers to the sheet, marks and thickness bumps',
          product: 'Surface marks and local thickness in the ply',
          consequence: 'Production', severity: 5, likelihood: 7,
          detection: 'Visual at the blade and on the sheet',
          signal: '',
          task: 'Inspect and re-load the blade each shift; replace on wear',
          interval: 'Each shift', pf: 3,
        },
        {
          fn: 'Drive all four rolls in the intended speed relationship',
          ff: 'Roll speeds drift apart',
          mode: 'Gear train backlash or drive encoder fault',
          effect: 'Speed relationship wanders and the sheet is drawn between rolls',
          product: 'Cord distortion and gauge ripple',
          consequence: 'Production', severity: 7, likelihood: 3,
          detection: 'Encoder comparison between drives; backlash measured at shutdown',
          signal: 'Drive speed error between rolls (%)',
          task: 'Compare drive speeds weekly; measure backlash at planned shutdown',
          interval: 'Weekly · annual measurement', pf: 60,
        },
      ],
    },

    {
      kind: 'Steel Cord Creel & Let-Off',
      stopHours: 2,
      stage: 'calendering',
      criticality: 'Medium',
      purpose: 'Feed steel cord at even tension and correct spacing into the calender.',
      modes: [
        {
          fn: 'Feed every cord at the set tension',
          ff: 'Cord tension varies between ends',
          mode: 'Creel brake pad wear or contamination',
          effect: 'Slack and tight ends across the width',
          product: 'Cord spacing (ends per inch) out of specification — a belt that will not perform as designed',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'Tension survey across the creel and pad thickness check',
          signal: 'Cord tension (N) per position',
          task: 'Tension survey weekly; replace brake pads as a set on wear',
          interval: 'Weekly', pf: 21,
        },
        {
          fn: 'Report cord tension truthfully to the control system',
          ff: 'Indicated tension is not the real tension',
          mode: 'Load cell drift — the reading looks correct while the cord is not',
          effect: 'Control holds the wrong tension and nothing alarms',
          product: 'Spacing and coating faults produced for as long as the drift goes unnoticed',
          consequence: 'Hidden', severity: 8, likelihood: 4,
          detection: 'Only by calibration against a reference load',
          signal: '',
          task: 'Calibrate load cells against a reference weight',
          interval: '6-monthly', pf: 0,
        },
        {
          fn: 'Guide cord without damaging it',
          ff: 'Cord is damaged in the guides',
          mode: 'Guide roller groove wear',
          effect: 'Filament breakage and fraying at the guides',
          product: 'Broken filaments in the belt — a durability failure that leaves the plant undetected',
          consequence: 'Production', severity: 8, likelihood: 5,
          detection: 'Guide inspection and broken-filament count at the calender',
          signal: '',
          task: 'Inspect guides monthly; replace grooved rollers',
          interval: 'Monthly', pf: 30,
        },
      ],
    },

    {
      kind: 'Bead Winder & Apex Applicator',
      stopHours: 3,
      stage: 'components',
      criticality: 'High',
      purpose: 'Wind the bead bundle to size and apply the apex profile to it.',
      modes: [
        {
          fn: 'Wind the bead to the specified diameter and turn count',
          ff: 'Bead diameter or turn count is out of specification',
          mode: 'Wire tension drift or spool brake wear',
          effect: 'Bundle diameter drifts across a shift',
          product: 'Bead seat and rim fit out of tolerance — the tyre will not seat correctly',
          consequence: 'Production', severity: 9, likelihood: 5,
          detection: 'First-off bead measurement each changeover and tension monitoring',
          signal: 'Wire tension (N)',
          task: 'Measure first-off at every changeover; verify tension weekly',
          interval: 'Every changeover', pf: 14,
        },
        {
          fn: 'Join the bead wire ends securely',
          ff: 'The bead splice is weak',
          mode: 'Welder or splicer element degradation',
          effect: 'Weld strength falls below specification without a visible change',
          product: 'A bead that can fail in service — the most serious defect this plant can ship',
          consequence: 'Safety', severity: 10, likelihood: 3,
          detection: 'Destructive pull test on samples; weld current monitoring',
          signal: 'Weld current (A) and time (ms)',
          task: 'Pull-test samples each shift; verify weld parameters and electrode condition weekly',
          interval: 'Each shift', pf: 7,
        },
        {
          fn: 'Apply the apex to the bead at the specified profile',
          ff: 'Apex profile or position is wrong',
          mode: 'Apex die wear or applicator misalignment',
          effect: 'Profile spreads, apex sits off centre on the bead',
          product: 'Uniformity failures and sidewall stiffness variation',
          consequence: 'Production', severity: 7, likelihood: 5,
          detection: 'Profile check at changeover; die inspection',
          signal: '',
          task: 'Check apex profile at every changeover; replace dies on wear',
          interval: 'Every changeover', pf: 21,
        },
      ],
    },

    {
      kind: 'Ply Cutter & Splicer',
      stopHours: 3,
      stage: 'components',
      criticality: 'High',
      purpose: 'Cut ply and steel cord fabric to length and angle, and splice it into a continuous feed.',
      modes: [
        {
          fn: 'Cut to the specified length and angle',
          ff: 'Cut length or angle is out of tolerance',
          mode: 'Blade wear or servo index drift',
          effect: 'Cut angle wanders; edges fray',
          product: 'Ply angle error — directly a uniformity and endurance defect in the tyre',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'First-off length and angle check; blade inspection',
          signal: 'Servo position error (mm)',
          task: 'First-off check every changeover; replace blades on a cut count',
          interval: 'Every changeover · blades on count', pf: 10,
        },
        {
          fn: 'Splice ply ends within the overlap specification',
          ff: 'The splice is open or overlapped too far',
          mode: 'Splicer heating element or pressure roller failure',
          effect: 'Splice will not hold; ply separates before building',
          product: 'Open splice in the carcass — a visible defect at inspection, a separation if it escapes',
          consequence: 'Production', severity: 9, likelihood: 5,
          detection: 'Splice measurement on first-off and element resistance check',
          signal: 'Splice element temperature (°C)',
          task: 'Measure splice overlap at every changeover; check element resistance monthly',
          interval: 'Every changeover', pf: 14,
        },
        {
          fn: 'Convey fabric without slip',
          ff: 'Fabric slips on the conveyor',
          mode: 'Vacuum loss or belt wear at the transfer',
          effect: 'Registration lost between cutting and splicing',
          product: 'Splice gaps and ply distortion',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Vacuum pressure and registration error trend',
          signal: 'Conveyor vacuum (kPa)',
          task: 'Check vacuum weekly; replace belts on wear',
          interval: 'Weekly', pf: 21,
        },
      ],
    },

    {
      kind: 'Tyre Building Machine',
      stopHours: 4,
      stage: 'building',
      criticality: 'High',
      purpose: 'Assemble the carcass, belts and tread into a green tyre to dimension and placement tolerance.',
      modes: [
        {
          fn: 'Present a drum of the correct diameter and profile',
          ff: 'Drum size or profile is out of tolerance',
          mode: 'Drum segment wear or segment return spring failure',
          effect: 'Segments no longer close to a true circle; diameter drifts',
          product: 'Green tyre dimension out of tolerance — uniformity failure after cure',
          consequence: 'Production', severity: 8, likelihood: 5,
          detection: 'Drum diameter measured at changeover; segment inspection',
          signal: 'Drum position feedback (mm)',
          task: 'Measure drum diameter at each size changeover; inspect segments and springs monthly',
          interval: 'Every changeover · monthly inspection', pf: 30,
        },
        {
          fn: 'Place each component at the specified position',
          ff: 'A component is placed off position',
          mode: 'Transfer ring gripper pad wear or servo encoder drift',
          effect: 'Belts and tread land off centre; the machine cannot see it',
          product: 'Conicity and lateral force variation — rejected at uniformity, or a pull complaint in service',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'Placement check on first-off tyres; encoder comparison; pad thickness',
          signal: 'Transfer servo position error (mm)',
          task: 'First-off placement check each shift; replace gripper pads on wear; verify encoders 6-monthly',
          interval: 'Each shift', pf: 21,
        },
        {
          fn: 'Stitch components together without trapping air',
          ff: 'Air is trapped between components',
          mode: 'Stitcher roller bearing seizure or spring pressure loss',
          effect: 'Stitching pressure falls; rollers skid instead of rolling',
          product: 'Trapped air — blisters and separations found at X-ray, or later in service',
          consequence: 'Production', severity: 9, likelihood: 5,
          detection: 'Roller free-rotation check and stitch pressure verification',
          signal: 'Stitcher cylinder pressure (bar)',
          task: 'Check every roller turns freely each shift; verify stitch pressure weekly',
          interval: 'Each shift', pf: 14,
        },
        {
          fn: 'Set both beads at the specified spacing',
          ff: 'Bead spacing is wrong',
          mode: 'Bead setter ring wear or misalignment',
          effect: 'Beads set unevenly; carcass pulled out of shape at shaping',
          product: 'Bead seat variation and sidewall indentation',
          consequence: 'Production', severity: 7, likelihood: 4,
          detection: 'Bead spacing measured on first-off; setter alignment check',
          signal: '',
          task: 'Measure bead spacing at changeover; align setters quarterly',
          interval: 'Every changeover', pf: 30,
        },
        {
          fn: 'Stop all motion when the light curtain is broken',
          ff: 'The machine does not stop when the guard is broken',
          mode: 'Light curtain or safety relay failure — silent until someone reaches in',
          effect: 'None in normal running',
          product: 'None — this one protects the builder',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Only by function test with a test rod',
          signal: '',
          task: 'Function-test the light curtain and safety relay; record the stopping time',
          interval: 'Monthly test', pf: 0,
        },
      ],
    },

    {
      kind: 'Curing Press',
      stopHours: 6,
      stage: 'curing',
      criticality: 'High',
      purpose: 'Hold the mould closed and deliver the cure recipe — time, temperature and pressure — to every tyre.',
      modes: [
        {
          fn: 'Hold the mould closed against internal pressure for the full cure',
          ff: 'The mould opens or loses clamping force during cure',
          mode: 'Hydraulic clamping pressure loss — cylinder seal or accumulator pre-charge',
          effect: 'Mould creeps open under pressure; press trips or the tyre flashes badly',
          product: 'Heavy flash and dimensional loss — scrap; a mould opening under load is also a release of steam',
          consequence: 'Safety', severity: 9, likelihood: 4,
          detection: 'Clamping pressure held during cure and accumulator pre-charge check',
          signal: 'Clamp pressure (bar) held through the cycle',
          task: 'Alarm on clamp pressure decay in-cycle; test accumulator pre-charge quarterly',
          interval: 'Every cycle · quarterly test', pf: 30,
        },
        {
          fn: 'Hold the mould at cure temperature across its whole face',
          ff: 'Part of the mould is below cure temperature',
          mode: 'Platen steam channel fouling or steam trap failure passing condensate',
          effect: 'Condensate lies in the platen; that zone runs cold and nothing on the panel says so',
          product: 'Under-cure in one region — the defect that passes visual inspection and fails in service',
          consequence: 'Production', severity: 10, likelihood: 6,
          detection: 'Thermal survey of the mould face; trap survey by temperature or ultrasound',
          signal: 'Platen temperature per zone (°C)',
          task: 'Steam trap survey monthly; thermal survey of mould faces quarterly; descale platens annually',
          interval: 'Monthly', pf: 30,
        },
        {
          fn: 'Load and unload the tyre without deforming it',
          ff: 'The tyre is deformed during loading',
          mode: 'Loader chuck pad wear or misalignment',
          effect: 'Green tyre grabbed off centre and distorted before the mould closes',
          product: 'Distorted green tyre — uniformity rejects traced back to the press, not the builder',
          consequence: 'Production', severity: 7, likelihood: 5,
          detection: 'Loader alignment check and pad inspection',
          signal: '',
          task: 'Inspect chuck pads monthly; align loader at each mould change',
          interval: 'Monthly', pf: 21,
        },
        {
          fn: 'Complete each cure to the recipe time',
          ff: 'The cycle is cut short or over-runs',
          mode: 'Sequence valve or timer fault',
          effect: 'Cycle length varies between presses running the same size',
          product: 'Under-cure or over-cure across a whole shift of output',
          consequence: 'Production', severity: 9, likelihood: 3,
          detection: 'Cycle time distribution per press from the PLC',
          signal: 'Cure cycle time (s) per press',
          task: 'Compare cycle time across presses weekly; investigate any press outside the band',
          interval: 'Weekly', pf: 14,
        },
        {
          fn: 'Prevent the press opening while under pressure',
          ff: 'The dome lock or interlock does not hold',
          mode: 'Dome lock limit switch or interlock failure — hidden until the day it matters',
          effect: 'Nothing visible in normal running',
          product: 'None — a steam and pressure release into an occupied aisle',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Only by function test of the interlock chain',
          signal: '',
          task: 'Function-test the dome lock and pressure interlock',
          interval: '6-monthly test', pf: 0,
        },
      ],
    },

    {
      kind: 'Curing Bladder & Mould',
      stopHours: 2,
      stage: 'curing',
      criticality: 'High',
      purpose: 'Shape the tyre from inside and form the tread pattern and sidewall detail.',
      modes: [
        {
          fn: 'Contain shaping pressure for the whole cure',
          ff: 'The bladder bursts in cycle',
          mode: 'Bladder fatigue at end of life',
          effect: 'Cure lost, mould and press contaminated, an hour to clean and re-fit',
          product: 'The tyre in the press is scrap',
          consequence: 'Production', severity: 8, likelihood: 7,
          detection: 'Cycle count against the bladder’s rated life; leak rate at shaping',
          signal: 'Bladder cycle count',
          task: 'Replace on cycle count rather than on failure; trend shaping pressure decay',
          interval: 'On cycle count', pf: 20,
        },
        {
          fn: 'Let trapped air escape from the mould cavity',
          ff: 'Air cannot escape at the mould face',
          mode: 'Mould vent blockage with cured rubber',
          effect: 'Air trapped between tyre and mould face',
          product: 'Bare spots and light tread detail — a cosmetic reject, in volume',
          consequence: 'Production', severity: 6, likelihood: 8,
          detection: 'Blind-vent survey of the mould; defect pattern by mould number',
          signal: '',
          task: 'Vent-clean each mould at a set cycle count; survey blind vents at every mould change',
          interval: 'On cycle count', pf: 14,
        },
        {
          fn: 'Form the pattern to the drawing',
          ff: 'The moulded shape is wrong',
          mode: 'Mould wear, damage or mismatch at the parting line',
          effect: 'Pattern detail rounds off; halves no longer match',
          product: 'Appearance rejects and tread depth below specification',
          consequence: 'Production', severity: 7, likelihood: 4,
          detection: 'Mould inspection in the mould shop at each change; tread depth checks',
          signal: '',
          task: 'Inspect and record mould condition at every change; refurbish on the schedule',
          interval: 'Every mould change', pf: 45,
        },
        {
          fn: 'Release the cured tyre cleanly',
          ff: 'The tyre sticks in the mould',
          mode: 'Release agent system blockage or wrong dilution',
          effect: 'Tyre tears on extraction; press stops while it is freed',
          product: 'Torn sidewall lettering; scrap',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Spray pattern check and dilution test',
          signal: '',
          task: 'Check spray pattern each shift; test dilution weekly',
          interval: 'Each shift', pf: 7,
        },
      ],
    },

    {
      kind: 'Post-Cure Inflator',
      stopHours: 2,
      stage: 'curing',
      criticality: 'Medium',
      purpose: 'Hold the tyre inflated while it cools so it keeps its moulded dimensions.',
      modes: [
        {
          fn: 'Hold inflation pressure through the cooling period',
          ff: 'Pressure is lost during cooling',
          mode: 'Rim seal leak or valve failure',
          effect: 'Tyre cools partly deflated',
          product: 'Shrinkage and dimensional variation — uniformity rejects',
          consequence: 'Production', severity: 7, likelihood: 6,
          detection: 'Station pressure trace over the cooling period',
          signal: 'PCI station pressure (bar)',
          task: 'Trend pressure decay per station; replace rim seals on the trend',
          interval: 'Weekly', pf: 21,
        },
        {
          fn: 'Hold the tyre for the full cooling time',
          ff: 'The tyre is released early',
          mode: 'Sequence timer or index drive fault',
          effect: 'Stations index before the cooling time is complete',
          product: 'Dimensional growth after release',
          consequence: 'Production', severity: 6, likelihood: 4,
          detection: 'Station dwell time from the PLC',
          signal: 'Station dwell time (s)',
          task: 'Verify dwell against the recipe weekly',
          interval: 'Weekly', pf: 14,
        },
      ],
    },

    {
      kind: 'Tyre Uniformity Machine',
      stopHours: 3,
      stage: 'finishing',
      criticality: 'High',
      purpose: 'Measure force variation and run-out on every tyre, and grade or reject it.',
      modes: [
        {
          fn: 'Measure force variation to the stated accuracy',
          ff: 'The measurement is wrong',
          mode: 'Calibration drift — the machine reads confidently and incorrectly',
          effect: 'Nothing visible; the grading line simply becomes fiction',
          product: 'Good tyres scrapped and bad tyres shipped — both, at once, until someone checks',
          consequence: 'Hidden', severity: 9, likelihood: 4,
          detection: 'Only by running a master tyre of known values',
          signal: '',
          task: 'Run the master tyre and compare against its certified values',
          interval: 'Weekly master check', pf: 0,
        },
        {
          fn: 'Roll the tyre against a true load wheel',
          ff: 'The load wheel is not true',
          mode: 'Load wheel bearing wear or surface damage',
          effect: 'Wheel run-out adds its own signature to every measurement',
          product: 'Systematic false readings — whole batches graded wrongly',
          consequence: 'Production', severity: 8, likelihood: 4,
          detection: 'Wheel run-out measurement and bearing vibration',
          signal: 'Load wheel vibration (mm/s)',
          task: 'Measure load wheel run-out quarterly; vibration route monthly',
          interval: 'Quarterly', pf: 60,
        },
        {
          fn: 'Hold the tyre concentric on the chuck',
          ff: 'The tyre is held off centre',
          mode: 'Rim chuck wear or clamping pressure loss',
          effect: 'Mounting eccentricity read as tyre run-out',
          product: 'False rejects on radial run-out',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Chuck run-out check and clamp pressure',
          signal: 'Chuck clamp pressure (bar)',
          task: 'Check chuck run-out monthly; verify clamp pressure weekly',
          interval: 'Monthly', pf: 30,
        },
      ],
    },

    {
      kind: 'Tyre X-Ray Inspection Unit',
      stopHours: 4,
      stage: 'finishing',
      criticality: 'High',
      purpose: 'Find internal defects — cord displacement, splice opens, trapped air — before the tyre ships.',
      modes: [
        {
          fn: 'Produce an image good enough to show the defect',
          ff: 'Defects are not visible in the image',
          mode: 'X-ray tube output decay or detector degradation',
          effect: 'Image contrast falls slowly; operators adapt to it without noticing',
          product: 'Defective tyres passed — the failure the whole inspection exists to prevent',
          consequence: 'Hidden', severity: 10, likelihood: 4,
          detection: 'Image quality indicator on a reference test piece',
          signal: 'Tube current (mA) and kV at reference settings',
          task: 'Run the reference test piece and record the image quality indicator',
          interval: 'Each shift', pf: 0,
        },
        {
          fn: 'Keep radiation inside the enclosure',
          ff: 'Radiation escapes or the beam runs with the door open',
          mode: 'Door interlock or shutter failure — no symptom until it matters',
          effect: 'None in normal running',
          product: 'None — a dose to whoever opens the cabinet',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Only by interlock function test and a radiation survey',
          signal: '',
          task: 'Function-test every interlock and survey the enclosure with a meter',
          interval: '6-monthly, and after any door work', pf: 0,
        },
      ],
    },

    {
      kind: 'Steam Boiler',
      stopHours: 12,
      stage: 'utilities',
      criticality: 'High',
      purpose: 'Supply dry saturated steam at pressure to the curing hall.',
      modes: [
        {
          fn: 'Supply steam at the required pressure and dryness',
          ff: 'Steam pressure or quality falls away',
          mode: 'Waterside scale from feedwater quality drift',
          effect: 'Heat transfer falls, fuel per tonne of steam climbs, tube metal runs hot',
          product: 'Every press in the hall cures slow — under-cure across the plant',
          consequence: 'Production', severity: 9, likelihood: 5,
          detection: 'Feedwater and boiler water testing; stack temperature and fuel-to-steam ratio',
          signal: 'Stack temperature (°C) and fuel per tonne of steam',
          task: 'Test boiler water daily; trend stack temperature; descale on the trend',
          interval: 'Daily test', pf: 60,
        },
        {
          fn: 'Relieve pressure above the design limit',
          ff: 'The safety valve does not lift at set pressure',
          mode: 'Safety valve seized or set wrong — the definitive hidden failure',
          effect: 'None, until an over-pressure that nothing then relieves',
          product: 'None — this is the one that takes the boiler house with it',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Only by lift testing',
          signal: '',
          task: 'Lift-test the safety valves; overhaul and reset at the statutory interval',
          interval: 'Statutory · lift-test 6-monthly', pf: 0,
        },
        {
          fn: 'Maintain water level above the firing limit',
          ff: 'Water level falls below the limit with the burner firing',
          mode: 'Low-water cut-out failure, or feedwater pump failure with the cut-out untested',
          effect: 'Firing continues on a falling level',
          product: 'None — tube failure and a dangerous release',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Blow-down test of the level controls',
          // Drum level is instrumented, and it says nothing about this mode:
          // the level reads correctly while the cut-out that acts on it is
          // dead. A hidden failure is hidden behind a working gauge.
          signal: '',
          task: 'Blow-down test the low-water cut-outs; prove the standby feed pump',
          interval: 'Each shift test', pf: 0,
        },
        {
          fn: 'Burn fuel completely and safely',
          ff: 'Combustion is unstable or unsafe',
          mode: 'Burner flame scanner or fuel valve degradation',
          effect: 'Lockouts and restarts, or unburnt fuel in the furnace',
          product: 'Steam interruption to the curing hall',
          consequence: 'Safety', severity: 9, likelihood: 3,
          detection: 'Flame signal strength trend and combustion analysis',
          signal: 'Flame signal strength (%)',
          task: 'Trend flame signal; combustion service and valve proving test 6-monthly',
          interval: '6-monthly', pf: 45,
        },
      ],
    },

    {
      kind: 'Screw Air Compressor',
      stopHours: 8,
      stage: 'utilities',
      criticality: 'High',
      purpose: 'Supply clean dry compressed air to building machines, presses and conveying.',
      modes: [
        {
          fn: 'Deliver air at pressure to the ring main',
          ff: 'Delivery pressure falls below the plant minimum',
          mode: 'Air end bearing wear',
          effect: 'Vibration and temperature climb for weeks, then a seizure that takes the machine out for a month',
          product: 'Pressure loss stops building machines and press auxiliaries plant-wide',
          consequence: 'Production', severity: 10, likelihood: 4,
          detection: 'Air end vibration and discharge temperature trend; oil analysis',
          signal: 'Air end vibration (mm/s) and discharge temperature (°C)',
          task: 'Vibration route monthly; oil analysis quarterly; overhaul on the trend',
          interval: 'Monthly', pf: 90,
        },
        {
          fn: 'Deliver air free of oil carry-over',
          ff: 'Oil is carried into the air system',
          mode: 'Oil separator element saturation or rupture',
          effect: 'Separator differential rises; oil passes downstream',
          product: 'Oil on green components — adhesion failures that appear at cure',
          consequence: 'Production', severity: 8, likelihood: 5,
          detection: 'Separator differential pressure; oil carry-over test at the receiver',
          signal: 'Separator ΔP (bar)',
          task: 'Change the separator on ΔP; carry-over test quarterly',
          interval: 'On ΔP limit', pf: 30,
        },
        {
          fn: 'Deliver air dry enough for pneumatics and product contact',
          ff: 'Air dew point rises above specification',
          mode: 'Dryer refrigerant loss or drain valve failure',
          effect: 'Moisture passes to the ring main; drains pass air or stick shut',
          product: 'Water in press and TBM pneumatics; moisture marks on components',
          consequence: 'Production', severity: 7, likelihood: 6,
          detection: 'Pressure dew point measurement and drain function check',
          signal: 'Pressure dew point (°C)',
          task: 'Monitor dew point continuously; test drains monthly',
          interval: 'Monthly', pf: 21,
        },
      ],
    },

    {
      kind: 'Hydraulic Power Unit',
      stopHours: 6,
      stage: 'utilities',
      criticality: 'High',
      purpose: 'Supply clean hydraulic oil at pressure to the curing presses.',
      modes: [
        {
          fn: 'Supply oil clean enough for the valves it feeds',
          ff: 'Oil cleanliness is below the valve requirement',
          mode: 'Filter bypass or ingress through breathers and seals',
          effect: 'Particles reach proportional valves; spools stick and pressures drift',
          product: 'Presses lose clamp pressure or cycle inconsistently — cure variation',
          consequence: 'Production', severity: 8, likelihood: 6,
          detection: 'Oil particle count against the target class; filter differential',
          signal: 'Oil cleanliness (ISO code) and filter ΔP (bar)',
          task: 'Sample oil quarterly against the target class; change filters on ΔP; fit and check desiccant breathers',
          interval: 'Quarterly sample', pf: 60,
        },
        {
          fn: 'Hold system pressure at set point',
          ff: 'System pressure sags under demand',
          mode: 'Pump cartridge wear or relief valve drift',
          effect: 'Pressure falls when several presses call together',
          product: 'Clamp force low on the presses that called last — flash and scrap',
          consequence: 'Production', severity: 8, likelihood: 4,
          detection: 'Pressure trace under peak demand; pump case drain flow',
          signal: 'System pressure (bar) at peak demand',
          task: 'Measure case drain flow 6-monthly; verify relief setting annually',
          interval: '6-monthly', pf: 60,
        },
        {
          fn: 'Keep oil temperature within the working range',
          ff: 'Oil runs hot',
          mode: 'Cooler fouling or cooling water loss',
          effect: 'Viscosity falls, seal and valve life shortens',
          product: 'Progressive pressure drift across the press population',
          consequence: 'Production', severity: 6, likelihood: 5,
          detection: 'Tank temperature trend and cooler approach',
          signal: 'Oil tank temperature (°C)',
          task: 'Trend tank temperature; clean cooler on the approach trend',
          interval: 'Monthly', pf: 45,
        },
      ],
    },

    {
      kind: 'Water Chiller',
      stopHours: 6,
      stage: 'utilities',
      criticality: 'High',
      purpose: 'Supply chilled water to mill, calender and extruder roll temperature control.',
      modes: [
        {
          fn: 'Deliver chilled water at the set flow temperature',
          ff: 'Flow temperature rises above set point',
          mode: 'Refrigerant leak',
          effect: 'Capacity falls, compressor runs longer, approach temperature widens',
          product: 'Roll temperatures drift across mixing and calendering — tack and scorch problems',
          consequence: 'Environment', severity: 8, likelihood: 5,
          detection: 'Suction superheat and approach temperature trend; annual leak test',
          signal: 'Chilled water flow temperature (°C) and approach (K)',
          task: 'Trend approach temperature; leak-test to the refrigerant regulations and log charge',
          interval: 'Statutory leak test · trend weekly', pf: 45,
        },
        {
          fn: 'Reject heat at the condenser',
          ff: 'Heat rejection falls away',
          mode: 'Condenser or cooling tower fill fouling',
          effect: 'Head pressure climbs, efficiency falls, high-pressure trips in summer',
          product: 'Loss of roll temperature control at the worst time of year',
          consequence: 'Production', severity: 7, likelihood: 6,
          detection: 'Condenser approach and head pressure trend; water treatment results',
          signal: 'Condenser approach (K)',
          task: 'Clean condenser and fill packs on the approach trend; maintain water treatment',
          interval: 'Quarterly', pf: 60,
        },
      ],
    },

    {
      kind: 'Dust Collection Unit',
      stopHours: 4,
      stage: 'utilities',
      criticality: 'Medium',
      purpose: 'Capture carbon black and compounding dust at the mixing line.',
      modes: [
        {
          fn: 'Capture dust at the pick-up points',
          ff: 'Dust is not captured',
          mode: 'Filter blinding or bag rupture',
          effect: 'Suction falls at the hoods, or dust passes straight through to the stack',
          product: 'Dust settles on compound and components — contamination',
          consequence: 'Environment', severity: 8, likelihood: 6,
          detection: 'Filter differential pressure and stack opacity',
          signal: 'Filter ΔP (mbar)',
          task: 'Trend filter ΔP; inspect bags on the trend; keep stack monitoring current',
          interval: 'Weekly', pf: 30,
        },
        {
          fn: 'Detect and stop a spark reaching the filter house',
          ff: 'A spark reaches the collector',
          mode: 'Spark detection or explosion vent failure — unknown until the event',
          effect: 'None in normal running',
          product: 'None — a dust fire or explosion in the filter house',
          consequence: 'Hidden', severity: 10, likelihood: 2,
          detection: 'Only by testing the detection and suppression chain',
          signal: '',
          task: 'Function-test spark detection and inspect explosion vents',
          interval: '6-monthly test', pf: 0,
        },
      ],
    },
  ],
}

export default { key: 'tyre', label: 'Tyre manufacturing', ...library }
